export default {
  LOAD_TITLES_SUCCESS: 'LOAD_TITLES_SUCCESS',
  LOAD_TITLES_ERROR: 'LOAD_TITLES_ERROR',
  LOAD_MOVIE_ENDPOINTS_SUCCESS: 'LOAD_MOVIE_ENDPOINTS_SUCCESS',
  LOAD_MOVIE_ENDPOINTS_ERROR: 'LOAD_MOVIE_ENDPOINTS_ERROR',
  SEARCH_PLANET_SUCCESS: 'SEARCH_PLANET_SUCCESS',
  SEARCH_PLANET_ERROR: 'SEARCH_PLANET_ERROR',
  SET_USER_MOVIE: 'SET_USER_MOVIE',
}
